repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.0
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: husky-run-pre-commit
        name: husky
        language: system
        entry: .husky/pre-commit
        pass_filenames: false
        always_run: true