---
name: tests
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'
      - name: use pnpm
        uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: 8.12.0
          cache: 'pnpm'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - name: Install poetry
        run: |
          python -m pip install poetry==1.7.1
      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true
      - name: Cache the virtualenv
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
      - name: Install frontend dependencies
        run: |
          pnpm install
      - name: Install backend dependencies
        run: |
          python -m poetry install
      - name: Run tests
        run: |
          python -m poetry run pytest --cov=scribe backend/test  -sxv
      - uses: psf/black@stable
        with:
          options: "--check --diff"
          src: "./backend/src"
          version: "~= 23.12"
      - uses: isort/isort-action@v1
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run flake8 ./backend --count --show-source --statistics
      - name: check valid TypeScript
        run: |
          pnpm tsc --noEmit
      - name: Run eslint
        run: |
          pnpm run lint
      - name: Check prettier formatting
        run: |
          pnpm run format